// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlRVMmhNA48tcEHHANJ0XtwnZz6aZtstE',
    appId: '1:809446152002:web:d9809562036cebdd49dadb',
    messagingSenderId: '809446152002',
    projectId: 'projeto-final-pdm-4d220',
    authDomain: 'projeto-final-pdm-4d220.firebaseapp.com',
    storageBucket: 'projeto-final-pdm-4d220.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3s-JfOjYlupQfRi9qnm5QVLRVm9sFYkQ',
    appId: '1:809446152002:android:33e6d7344b75fa5949dadb',
    messagingSenderId: '809446152002',
    projectId: 'projeto-final-pdm-4d220',
    storageBucket: 'projeto-final-pdm-4d220.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpLxQv1JBiUY3XcyGnrJ0VPBMX9BshW4o',
    appId: '1:809446152002:ios:2279f2f0dd9b719349dadb',
    messagingSenderId: '809446152002',
    projectId: 'projeto-final-pdm-4d220',
    storageBucket: 'projeto-final-pdm-4d220.appspot.com',
    iosClientId: '809446152002-fi5f5ss24gm34ls65fkir4u1u5db9h3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpLxQv1JBiUY3XcyGnrJ0VPBMX9BshW4o',
    appId: '1:809446152002:ios:2279f2f0dd9b719349dadb',
    messagingSenderId: '809446152002',
    projectId: 'projeto-final-pdm-4d220',
    storageBucket: 'projeto-final-pdm-4d220.appspot.com',
    iosClientId: '809446152002-fi5f5ss24gm34ls65fkir4u1u5db9h3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
